//
// MaxMind GeoIP -> Convert text timezone locations to a separate lookup timezone table
//
// This takes in an locations file and spits out the same CSV but with the timezone
// column replaced with an index into the a timezone table rather than having the
// timezone location spelled out.
//
// The two tables are (in MySQL syntax):
//
// CREATE TABLE `locations` (
//   `geoname_id`              INT(10)       UNSIGNED NOT NULL DEFAULT '0',
//   `locale_code`             VARCHAR(2)             NOT NULL DEFAULT '',
//   `continent_code`          VARCHAR(2)             NOT NULL DEFAULT '',
//   `continent_name`          VARCHAR(40)            NOT NULL DEFAULT '',
//   `country_iso_code`        VARCHAR(2)             NOT NULL DEFAULT '',
//   `country_name`            VARCHAR(64)            NOT NULL DEFAULT '',
//   `subdivision_1_iso_code`  VARCHAR(3)             NOT NULL DEFAULT '',
//   `subdivision_1_name`      VARCHAR(100)           NOT NULL DEFAULT '',
//   `subdivision_2_iso_code`  VARCHAR(3)             NOT NULL DEFAULT '',
//   `subdivision_2_name`      VARCHAR(100)           NOT NULL DEFAULT '',
//   `city_name`               VARCHAR(100)           NOT NULL DEFAULT '',
//   `metro_code`              SMALLINT(5)   UNSIGNED DEFAULT NULL,
//   `timezoneid`              SMALLINT(3)   UNSIGNED NOT NULL DEFAULT '0',
//   PRIMARY KEY (`geoname_id`)
// ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
//
// CREATE TABLE `timezone` (
//   `timezoneid`  SMALLINT(3)  UNSIGNED NOT NULL AUTO_INCREMENT,
//   `timezone`    VARCHAR(40)           NOT NULL DEFAULT '',
//   PRIMARY KEY (`timezoneid`)
// ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
//
// TODO: Output to files instead of outputing both tables it stdout, this will
//       make it easier to import later on.
//

package main

import (
	"encoding/csv"
	"fmt"
	"io"
	"os"
)

// Keep track of all the timezones we've seen in a map
var timezones = map[string]int{
	"UTC":                              0,
	"Africa/Abidjan":                   1,
	"Africa/Accra":                     2,
	"Africa/Addis_Ababa":               3,
	"Africa/Algiers":                   4,
	"Africa/Asmara":                    5,
	"Africa/Asmera":                    6,
	"Africa/Bamako":                    7,
	"Africa/Bangui":                    8,
	"Africa/Banjul":                    9,
	"Africa/Bissau":                    10,
	"Africa/Blantyre":                  11,
	"Africa/Brazzaville":               12,
	"Africa/Bujumbura":                 13,
	"Africa/Cairo":                     14,
	"Africa/Casablanca":                15,
	"Africa/Ceuta":                     16,
	"Africa/Conakry":                   17,
	"Africa/Dakar":                     18,
	"Africa/Dar_es_Salaam":             19,
	"Africa/Djibouti":                  20,
	"Africa/Douala":                    21,
	"Africa/El_Aaiun":                  22,
	"Africa/Freetown":                  23,
	"Africa/Gaborone":                  24,
	"Africa/Harare":                    25,
	"Africa/Johannesburg":              26,
	"Africa/Kampala":                   27,
	"Africa/Khartoum":                  28,
	"Africa/Kigali":                    29,
	"Africa/Kinshasa":                  30,
	"Africa/Lagos":                     31,
	"Africa/Libreville":                32,
	"Africa/Lome":                      33,
	"Africa/Luanda":                    34,
	"Africa/Lubumbashi":                35,
	"Africa/Lusaka":                    36,
	"Africa/Malabo":                    37,
	"Africa/Maputo":                    38,
	"Africa/Maseru":                    39,
	"Africa/Mbabane":                   40,
	"Africa/Mogadishu":                 41,
	"Africa/Monrovia":                  42,
	"Africa/Nairobi":                   43,
	"Africa/Ndjamena":                  44,
	"Africa/Niamey":                    45,
	"Africa/Nouakchott":                46,
	"Africa/Ouagadougou":               47,
	"Africa/Porto-Novo":                48,
	"Africa/Sao_Tome":                  49,
	"Africa/Timbuktu":                  50,
	"Africa/Tripoli":                   51,
	"Africa/Tunis":                     52,
	"Africa/Windhoek":                  53,
	"America/Adak":                     54,
	"America/Anchorage":                55,
	"America/Anguilla":                 56,
	"America/Antigua":                  57,
	"America/Araguaina":                58,
	"America/Argentina/Buenos_Aires":   59,
	"America/Argentina/Catamarca":      60,
	"America/Argentina/ComodRivadavia": 61,
	"America/Argentina/Cordoba":        62,
	"America/Argentina/Jujuy":          63,
	"America/Argentina/La_Rioja":       64,
	"America/Argentina/Mendoza":        65,
	"America/Argentina/Rio_Gallegos":   66,
	"America/Argentina/San_Juan":       67,
	"America/Argentina/Tucuman":        68,
	"America/Argentina/Ushuaia":        69,
	"America/Aruba":                    70,
	"America/Asuncion":                 71,
	"America/Atikokan":                 72,
	"America/Atka":                     73,
	"America/Bahia":                    74,
	"America/Barbados":                 75,
	"America/Belem":                    76,
	"America/Belize":                   77,
	"America/Blanc-Sablon":             78,
	"America/Boa_Vista":                79,
	"America/Bogota":                   80,
	"America/Boise":                    81,
	"America/Buenos_Aires":             82,
	"America/Cambridge_Bay":            83,
	"America/Campo_Grande":             84,
	"America/Cancun":                   85,
	"America/Caracas":                  86,
	"America/Catamarca":                87,
	"America/Cayenne":                  88,
	"America/Cayman":                   89,
	"America/Chicago":                  90,
	"America/Chihuahua":                91,
	"America/Coral_Harbour":            92,
	"America/Cordoba":                  93,
	"America/Costa_Rica":               94,
	"America/Cuiaba":                   95,
	"America/Curacao":                  96,
	"America/Danmarkshavn":             97,
	"America/Dawson":                   98,
	"America/Dawson_Creek":             99,
	"America/Denver":                   100,
	"America/Detroit":                  101,
	"America/Dominica":                 102,
	"America/Edmonton":                 103,
	"America/Eirunepe":                 104,
	"America/El_Salvador":              105,
	"America/Ensenada":                 106,
	"America/Fort_Wayne":               107,
	"America/Fortaleza":                108,
	"America/Glace_Bay":                109,
	"America/Godthab":                  110,
	"America/Goose_Bay":                111,
	"America/Grand_Turk":               112,
	"America/Grenada":                  113,
	"America/Guadeloupe":               114,
	"America/Guatemala":                115,
	"America/Guayaquil":                116,
	"America/Guyana":                   117,
	"America/Halifax":                  118,
	"America/Havana":                   119,
	"America/Hermosillo":               120,
	"America/Indiana/Indianapolis":     121,
	"America/Indiana/Knox":             122,
	"America/Indiana/Marengo":          123,
	"America/Indiana/Petersburg":       124,
	"America/Indiana/Tell_City":        125,
	"America/Indiana/Vevay":            126,
	"America/Indiana/Vincennes":        127,
	"America/Indiana/Winamac":          128,
	"America/Indianapolis":             129,
	"America/Inuvik":                   130,
	"America/Iqaluit":                  131,
	"America/Jamaica":                  132,
	"America/Jujuy":                    133,
	"America/Juneau":                   134,
	"America/Kentucky/Louisville":      135,
	"America/Kentucky/Monticello":      136,
	"America/Knox_IN":                  137,
	"America/La_Paz":                   138,
	"America/Lima":                     139,
	"America/Los_Angeles":              140,
	"America/Louisville":               141,
	"America/Maceio":                   142,
	"America/Managua":                  143,
	"America/Manaus":                   144,
	"America/Marigot":                  145,
	"America/Martinique":               146,
	"America/Mazatlan":                 147,
	"America/Mendoza":                  148,
	"America/Menominee":                149,
	"America/Merida":                   150,
	"America/Mexico_City":              151,
	"America/Miquelon":                 152,
	"America/Moncton":                  153,
	"America/Monterrey":                154,
	"America/Montevideo":               155,
	"America/Montreal":                 156,
	"America/Montserrat":               157,
	"America/Nassau":                   158,
	"America/New_York":                 159,
	"America/Nipigon":                  160,
	"America/Nome":                     161,
	"America/Noronha":                  162,
	"America/North_Dakota/Center":      163,
	"America/North_Dakota/New_Salem":   164,
	"America/Panama":                   165,
	"America/Pangnirtung":              166,
	"America/Paramaribo":               167,
	"America/Phoenix":                  168,
	"America/Port-au-Prince":           169,
	"America/Port_of_Spain":            170,
	"America/Porto_Acre":               171,
	"America/Porto_Velho":              172,
	"America/Puerto_Rico":              173,
	"America/Rainy_River":              174,
	"America/Rankin_Inlet":             175,
	"America/Recife":                   176,
	"America/Regina":                   177,
	"America/Resolute":                 178,
	"America/Rio_Branco":               179,
	"America/Rosario":                  180,
	"America/Santiago":                 181,
	"America/Santo_Domingo":            182,
	"America/Sao_Paulo":                183,
	"America/Scoresbysund":             184,
	"America/Shiprock":                 185,
	"America/St_Barthelemy":            186,
	"America/St_Johns":                 187,
	"America/St_Kitts":                 188,
	"America/St_Lucia":                 189,
	"America/St_Thomas":                190,
	"America/St_Vincent":               191,
	"America/Swift_Current":            192,
	"America/Tegucigalpa":              193,
	"America/Thule":                    194,
	"America/Thunder_Bay":              195,
	"America/Tijuana":                  196,
	"America/Toronto":                  197,
	"America/Tortola":                  198,
	"America/Vancouver":                199,
	"America/Virgin":                   200,
	"America/Whitehorse":               201,
	"America/Winnipeg":                 202,
	"America/Yakutat":                  203,
	"America/Yellowknife":              204,
	"Antarctica/Casey":                 205,
	"Antarctica/Davis":                 206,
	"Antarctica/DumontDUrville":        207,
	"Antarctica/Mawson":                208,
	"Antarctica/McMurdo":               209,
	"Antarctica/Palmer":                210,
	"Antarctica/Rothera":               211,
	"Antarctica/South_Pole":            212,
	"Antarctica/Syowa":                 213,
	"Antarctica/Vostok":                214,
	"Arctic/Longyearbyen":              215,
	"Asia/Aden":                        216,
	"Asia/Almaty":                      217,
	"Asia/Amman":                       218,
	"Asia/Anadyr":                      219,
	"Asia/Aqtau":                       220,
	"Asia/Aqtobe":                      221,
	"Asia/Ashgabat":                    222,
	"Asia/Ashkhabad":                   223,
	"Asia/Baghdad":                     224,
	"Asia/Bahrain":                     225,
	"Asia/Baku":                        226,
	"Asia/Bangkok":                     227,
	"Asia/Beirut":                      228,
	"Asia/Bishkek":                     229,
	"Asia/Brunei":                      230,
	"Asia/Calcutta":                    231,
	"Asia/Choibalsan":                  232,
	"Asia/Chongqing":                   233,
	"Asia/Chungking":                   234,
	"Asia/Colombo":                     235,
	"Asia/Dacca":                       236,
	"Asia/Damascus":                    237,
	"Asia/Dhaka":                       238,
	"Asia/Dili":                        239,
	"Asia/Dubai":                       240,
	"Asia/Dushanbe":                    241,
	"Asia/Gaza":                        242,
	"Asia/Harbin":                      243,
	"Asia/Hong_Kong":                   244,
	"Asia/Hovd":                        245,
	"Asia/Irkutsk":                     246,
	"Asia/Istanbul":                    247,
	"Asia/Jakarta":                     248,
	"Asia/Jayapura":                    249,
	"Asia/Jerusalem":                   250,
	"Asia/Kabul":                       251,
	"Asia/Kamchatka":                   252,
	"Asia/Karachi":                     253,
	"Asia/Kashgar":                     254,
	"Asia/Katmandu":                    255,
	"Asia/Krasnoyarsk":                 256,
	"Asia/Kuala_Lumpur":                257,
	"Asia/Kuching":                     258,
	"Asia/Kuwait":                      259,
	"Asia/Macao":                       260,
	"Asia/Macau":                       261,
	"Asia/Magadan":                     262,
	"Asia/Makassar":                    263,
	"Asia/Manila":                      264,
	"Asia/Muscat":                      265,
	"Asia/Nicosia":                     266,
	"Asia/Novosibirsk":                 267,
	"Asia/Omsk":                        268,
	"Asia/Oral":                        269,
	"Asia/Phnom_Penh":                  270,
	"Asia/Pontianak":                   271,
	"Asia/Pyongyang":                   272,
	"Asia/Qatar":                       273,
	"Asia/Qyzylorda":                   274,
	"Asia/Rangoon":                     275,
	"Asia/Riyadh":                      276,
	"Asia/Riyadh87":                    277,
	"Asia/Riyadh88":                    278,
	"Asia/Riyadh89":                    279,
	"Asia/Saigon":                      280,
	"Asia/Sakhalin":                    281,
	"Asia/Samarkand":                   282,
	"Asia/Seoul":                       283,
	"Asia/Shanghai":                    284,
	"Asia/Singapore":                   285,
	"Asia/Taipei":                      286,
	"Asia/Tashkent":                    287,
	"Asia/Tbilisi":                     288,
	"Asia/Tehran":                      289,
	"Asia/Tel_Aviv":                    290,
	"Asia/Thimbu":                      291,
	"Asia/Thimphu":                     292,
	"Asia/Tokyo":                       293,
	"Asia/Ujung_Pandang":               294,
	"Asia/Ulaanbaatar":                 295,
	"Asia/Ulan_Bator":                  296,
	"Asia/Urumqi":                      297,
	"Asia/Vientiane":                   298,
	"Asia/Vladivostok":                 299,
	"Asia/Yakutsk":                     300,
	"Asia/Yekaterinburg":               301,
	"Asia/Yerevan":                     302,
	"Atlantic/Azores":                  303,
	"Atlantic/Bermuda":                 304,
	"Atlantic/Canary":                  305,
	"Atlantic/Cape_Verde":              306,
	"Atlantic/Faeroe":                  307,
	"Atlantic/Faroe":                   308,
	"Atlantic/Jan_Mayen":               309,
	"Atlantic/Madeira":                 310,
	"Atlantic/Reykjavik":               311,
	"Atlantic/South_Georgia":           312,
	"Atlantic/St_Helena":               313,
	"Atlantic/Stanley":                 314,
	"Australia/ACT":                    315,
	"Australia/Adelaide":               316,
	"Australia/Brisbane":               317,
	"Australia/Broken_Hill":            318,
	"Australia/Canberra":               319,
	"Australia/Currie":                 320,
	"Australia/Darwin":                 321,
	"Australia/Eucla":                  322,
	"Australia/Hobart":                 323,
	"Australia/LHI":                    324,
	"Australia/Lindeman":               325,
	"Australia/Lord_Howe":              326,
	"Australia/Melbourne":              327,
	"Australia/NSW":                    328,
	"Australia/North":                  329,
	"Australia/Perth":                  330,
	"Australia/Queensland":             331,
	"Australia/South":                  332,
	"Australia/Sydney":                 333,
	"Australia/Tasmania":               334,
	"Australia/Victoria":               335,
	"Australia/West":                   336,
	"Australia/Yancowinna":             337,
	"Brazil/Acre":                      338,
	"Brazil/DeNoronha":                 339,
	"Brazil/East":                      340,
	"Brazil/West":                      341,
	"CET":                              342,
	"CST6CDT":                          343,
	"Canada/Atlantic":                  344,
	"Canada/Central":                   345,
	"Canada/East-Saskatchewan":         346,
	"Canada/Eastern":                   347,
	"Canada/Mountain":                  348,
	"Canada/Newfoundland":              349,
	"Canada/Pacific":                   350,
	"Canada/Saskatchewan":              351,
	"Canada/Yukon":                     352,
	"Chile/Continental":                353,
	"Chile/EasterIsland":               354,
	"Cuba":                             355,
	"EET":                              356,
	"EST":                              357,
	"EST5EDT":                          358,
	"Egypt":                            359,
	"Eire":                             360,
	"Etc/GMT":                          361,
	"Etc/GMT+0":                        362,
	"Etc/GMT+1":                        363,
	"Etc/GMT+10":                       364,
	"Etc/GMT+11":                       365,
	"Etc/GMT+12":                       366,
	"Etc/GMT+2":                        367,
	"Etc/GMT+3":                        368,
	"Etc/GMT+4":                        369,
	"Etc/GMT+5":                        370,
	"Etc/GMT+6":                        371,
	"Etc/GMT+7":                        372,
	"Etc/GMT+8":                        373,
	"Etc/GMT+9":                        374,
	"Etc/GMT-0":                        375,
	"Etc/GMT-1":                        376,
	"Etc/GMT-10":                       377,
	"Etc/GMT-11":                       378,
	"Etc/GMT-12":                       379,
	"Etc/GMT-13":                       380,
	"Etc/GMT-14":                       381,
	"Etc/GMT-2":                        382,
	"Etc/GMT-3":                        383,
	"Etc/GMT-4":                        384,
	"Etc/GMT-5":                        385,
	"Etc/GMT-6":                        386,
	"Etc/GMT-7":                        387,
	"Etc/GMT-8":                        388,
	"Etc/GMT-9":                        389,
	"Etc/GMT0":                         390,
	"Etc/Greenwich":                    391,
	"Etc/UCT":                          392,
	"Etc/UTC":                          393,
	"Etc/Universal":                    394,
	"Etc/Zulu":                         395,
	"Europe/Amsterdam":                 396,
	"Europe/Andorra":                   397,
	"Europe/Athens":                    398,
	"Europe/Belfast":                   399,
	"Europe/Belgrade":                  400,
	"Europe/Berlin":                    401,
	"Europe/Bratislava":                402,
	"Europe/Brussels":                  403,
	"Europe/Bucharest":                 404,
	"Europe/Budapest":                  405,
	"Europe/Chisinau":                  406,
	"Europe/Copenhagen":                407,
	"Europe/Dublin":                    408,
	"Europe/Gibraltar":                 409,
	"Europe/Guernsey":                  410,
	"Europe/Helsinki":                  411,
	"Europe/Isle_of_Man":               412,
	"Europe/Istanbul":                  413,
	"Europe/Jersey":                    414,
	"Europe/Kaliningrad":               415,
	"Europe/Kiev":                      416,
	"Europe/Lisbon":                    417,
	"Europe/Ljubljana":                 418,
	"Europe/London":                    419,
	"Europe/Luxembourg":                420,
	"Europe/Madrid":                    421,
	"Europe/Malta":                     422,
	"Europe/Mariehamn":                 423,
	"Europe/Minsk":                     424,
	"Europe/Monaco":                    425,
	"Europe/Moscow":                    426,
	"Europe/Nicosia":                   427,
	"Europe/Oslo":                      428,
	"Europe/Paris":                     429,
	"Europe/Podgorica":                 430,
	"Europe/Prague":                    431,
	"Europe/Riga":                      432,
	"Europe/Rome":                      433,
	"Europe/Samara":                    434,
	"Europe/San_Marino":                435,
	"Europe/Sarajevo":                  436,
	"Europe/Simferopol":                437,
	"Europe/Skopje":                    438,
	"Europe/Sofia":                     439,
	"Europe/Stockholm":                 440,
	"Europe/Tallinn":                   441,
	"Europe/Tirane":                    442,
	"Europe/Tiraspol":                  443,
	"Europe/Uzhgorod":                  444,
	"Europe/Vaduz":                     445,
	"Europe/Vatican":                   446,
	"Europe/Vienna":                    447,
	"Europe/Vilnius":                   448,
	"Europe/Volgograd":                 449,
	"Europe/Warsaw":                    450,
	"Europe/Zagreb":                    451,
	"Europe/Zaporozhye":                452,
	"Europe/Zurich":                    453,
	"Factory":                          454,
	"GB":                               455,
	"GB-Eire":                          456,
	"GMT":                              457,
	"GMT+0":                            458,
	"GMT-0":                            459,
	"GMT0":                             460,
	"Greenwich":                        461,
	"HST":                              462,
	"Hongkong":                         463,
	"Iceland":                          464,
	"Indian/Antananarivo":              465,
	"Indian/Chagos":                    466,
	"Indian/Christmas":                 467,
	"Indian/Cocos":                     468,
	"Indian/Comoro":                    469,
	"Indian/Kerguelen":                 470,
	"Indian/Mahe":                      471,
	"Indian/Maldives":                  472,
	"Indian/Mauritius":                 473,
	"Indian/Mayotte":                   474,
	"Indian/Reunion":                   475,
	"Iran":                             476,
	"Israel":                           477,
	"Jamaica":                          478,
	"Japan":                            479,
	"Kwajalein":                        480,
	"Libya":                            481,
	"MET":                              482,
	"MST":                              483,
	"MST7MDT":                          484,
	"Mexico/BajaNorte":                 485,
	"Mexico/BajaSur":                   486,
	"Mexico/General":                   487,
	"Mideast/Riyadh87":                 488,
	"Mideast/Riyadh88":                 489,
	"Mideast/Riyadh89":                 490,
	"NZ":                               491,
	"NZ-CHAT":                          492,
	"Navajo":                           493,
	"PRC":                              494,
	"PST8PDT":                          495,
	"Pacific/Apia":                     496,
	"Pacific/Auckland":                 497,
	"Pacific/Chatham":                  498,
	"Pacific/Easter":                   499,
	"Pacific/Efate":                    500,
	"Pacific/Enderbury":                501,
	"Pacific/Fakaofo":                  502,
	"Pacific/Fiji":                     503,
	"Pacific/Funafuti":                 504,
	"Pacific/Galapagos":                505,
	"Pacific/Gambier":                  506,
	"Pacific/Guadalcanal":              507,
	"Pacific/Guam":                     508,
	"Pacific/Honolulu":                 509,
	"Pacific/Johnston":                 510,
	"Pacific/Kiritimati":               511,
	"Pacific/Kosrae":                   512,
	"Pacific/Kwajalein":                513,
	"Pacific/Majuro":                   514,
	"Pacific/Marquesas":                515,
	"Pacific/Midway":                   516,
	"Pacific/Nauru":                    517,
	"Pacific/Niue":                     518,
	"Pacific/Norfolk":                  519,
	"Pacific/Noumea":                   520,
	"Pacific/Pago_Pago":                521,
	"Pacific/Palau":                    522,
	"Pacific/Pitcairn":                 523,
	"Pacific/Ponape":                   524,
	"Pacific/Port_Moresby":             525,
	"Pacific/Rarotonga":                526,
	"Pacific/Saipan":                   527,
	"Pacific/Samoa":                    528,
	"Pacific/Tahiti":                   529,
	"Pacific/Tarawa":                   530,
	"Pacific/Tongatapu":                531,
	"Pacific/Truk":                     532,
	"Pacific/Wake":                     533,
	"Pacific/Wallis":                   534,
	"Pacific/Yap":                      535,
	"Poland":                           536,
	"Portugal":                         537,
	"ROC":                              538,
	"ROK":                              539,
	"Singapore":                        540,
	"Turkey":                           541,
	"UCT":                              542,
	"US/Alaska":                        543,
	"US/Aleutian":                      544,
	"US/Arizona":                       545,
	"US/Central":                       546,
	"US/East-Indiana":                  547,
	"US/Eastern":                       548,
	"US/Hawaii":                        549,
	"US/Indiana-Starke":                550,
	"US/Michigan":                      551,
	"US/Mountain":                      552,
	"US/Pacific":                       553,
	"US/Pacific-New":                   554,
	"US/Samoa":                         555,
	"Universal":                        556,
	"W-SU":                             557,
	"WET":                              558,
	"Zulu":                             559,
}

func main() {

	inFile, _ := os.Open(os.Args[1])
	defer inFile.Close()
	reader := csv.NewReader(inFile)

	// Print the header line
	fmt.Println("geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,subdivision_1_iso_code,subdivision_1_name,subdivision_2_iso_code,subdivision_2_name,city_name,metro_code,time_zone")

	lineCount := 0
	timezoneid := 560 // The next timezone, 0 is assumed to be UTC
	for {
		record, err := reader.Read()
		if err != nil {
			if err != io.EOF {
				fmt.Fprintf(os.Stderr, "Error: %s\n", err.Error())
				return
			}
			break
		}

		lineCount++

		// The first line is the header line
		if lineCount == 1 {
			continue
		}

		// Get the timezone id for this timezone location
		tzid, ok := timezones[record[12]]
		if !ok {
			// Create the new timezone location in the map if it doesn't exist
			// and assign it a new timezoneid
			timezones[record[12]] = timezoneid
			tzid = timezoneid
			timezoneid++
		}

		fmt.Printf("%s,\"%s\",\"%s\",\"%s\",\"%s\",\"%s\",\"%s\",\"%s\",\"%s\",\"%s\",\"%s\",%s,%d\n",
			record[0], record[1], record[2], record[3], record[4], record[5],
			record[6], record[7], record[8], record[9], record[10], record[11], tzid)

	}

	fmt.Println("\ntimezoneid,timezone")
	// Dump a CSV for the timezones
	for k, v := range timezones {
		fmt.Printf("%d,\"%s\"\n", v, k)
	}
}
